set nocompatible

set autoindent
set smartindent

set list
set listchars=tab:>-,trail:-
set number
set shiftwidth=2
set showmatch
set softtabstop=2
set tabstop=4
set autoread
set backupdir=~/.backup//
set directory=~/.backup//
set expandtab
set guifont=Monaco:h14
set guioptions+=b "bottom scrollbar
set guitablabel=%M\ %t
set hidden
set hlsearch
set incsearch
set laststatus=2 "0-never,1-when 2+ windows,2-always
set ruler
set showmatch
set showcmd
set showmode
set statusline=%t\ %m
set nowrap
set wildmenu
set wildmode=list:longest,full

syntax enable
syntax on
"set background=dark
"colorscheme solarized

filetype on
filetype plugin on
filetype indent on

let &colorcolumn="120"
highlight ColorColumn guibg=#2c2d27

let g:acp_ignorecaseOption = 0
set completeopt=longest,menuone
set omnifunc=syntaxcomplete#Complete

autocmd BufRead,BufNewFile *.html.erb  set filetype=html
autocmd BufRead,BufNewFile *.yml.erb   set filetype=yaml
autocmd BufRead,BufNewFile *.sh.erb    set filetype=bash
autocmd BufRead,BufNewFile *.js.erb    set filetype=javascript
autocmd BufRead,BufNewFile *.js.coffee set filetype=javascript
autocmd BufRead,BufNewFile *.ejs       set filetype=html
autocmd BufRead,BufNewFile *.less      set filetype=css
autocmd BufRead,BufNewFile *.jsx       set filetype=javascript
autocmd BufRead,BufNewFile *.json      set filetype=javascript
